name: graphql_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  gql: ^1.0.0+1
  graphql: ^5.1.3
  # graphql_flutter: ^5.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  graphql_codegen: ^0.13.11
  build_runner: ^2.4.8
# flutter:
#   generate: true
